codefordenver/code-for-denver-site

index.html

updates slogan

---

index.html
js/cfapi.js
templates/projects.hbs
templates/projects.hbs.js

Basic scaffolding until this get pulled into a larger grunt/application.hbs structure.
@wdoug  for making template changes until we get grunt going:
- ```npm install -g handlebars```
- inside of ```templates/``` run ```handlebars projects.hbs -f projects.hbs.js```

handlebars scaffolding for projects

---

README.md

On-boarding / Getting Started documentation.

Onboarding

---

index.html

Can be re-added once we decide the design

Remove Partnerships and Data Resources

---

index.html
members/index.html

This is a new page (accessible currently just by direct link) for collecting some useful resources for members
Potentially closes #24

Members page

---

src/components/home/GetInvolved.js

removed github issue cards

---

Procfile
README.md
app.json
package.json
staticServer.js

Set up pr review apps through

---

2015/less/less.main.less
2015/src/cljs/review/app.cljs

switches banner colors from scrolling, makes banner opaque

---

2015/build.boot
2015/less/less.main.less
2015/resources/index.html
2015/src/cljs/review/app.cljs

@eemshi I switch to a different library for drawing the pie chart, let me know what you think.
connects to #112

adds pizza pie chart

---

src/components/Header.js
src/components/home/Partner.js
src/components/home/Volunteer.js
src/index.js
src/markdown/partner.md
src/markdown/volunteer.md
src/markdown/what_we_do.md

Redesign secondary

---

package.json
src/components/home/GetInvolved.js
src/components/home/Volunteer.js
static/css/style.css

Worked on this today
npm install was raising warning with Redux not being installed with React-Redux, so I added the dependency.
To start, just imported the GetInvolved.js component into Volunteer.js, then added it into the Volunter render method.
The old transition effects I couldn't get working, so I modified the GetInvolved component to set and manage a simple state referring to the index of the peopleTypes. When the component mounts, it sets a timer to call a state update function every 2 seconds. This timer gets cleared when the componenet unmounts.
I used the addon ReactCSSTransitionGroup to get some basic animations working. I've got very little experience working with transitions. There's a basic transition effect in the CSS.
Thoughts?

Worked on issue 134, adding the GetInvolved to Volunteer Component

---

package.json
src/components/segments/TwitterFeed.js

fixes TwitterFeed component, thanks @devin ;)

---

package.json
src/components/segments/Interested.js
static/css/style.css

Added Dynamic Date in Interested Component

Dynamic Date in Interested Panel

---

src/components/pages/WhatWeDo.js
static/css/style.css

Redesign zack

---

src/components/pages/CanWeHelpYou.js
src/components/pages/OurVoice.js
src/components/pages/WantToHelp.js
src/components/pages/WantToLearn.js
src/components/pages/WhatWeDo.js
src/index.js
static/css/style.css

Add in the changing hero images on tab change, fix nav background color, change support us tab into Want to Learn tab.

Redesign devin

---

src/components/Header.js
src/components/pages/WantToLearn.js

Fixed the header, and made a slight change to the WantToLearn page.

Modify header, and want to learn page.

---

src/components/pages/WhatWeDo.js
src/components/pages/WhoWeAre.js
src/components/segments/Statistics.js
src/components/segments/TheCommunity.js
src/markdown/howitworks.md
src/markdown/projects.md
src/markdown/skillsandlanguages.md
static/css/style.css

-moves Interested tab to bottom of page
-updates text on page markdown files
-adds classes for h3, h4, and blockquote

Content update for What We Do page

---

Procfile
README.md
app.json
package.json
src/components/home/GetInvolved.js
src/markdown/nonprofit-partnership-program.md
staticServer.js

This reverts commit 0b493ab8bd846ff9f2943f56d2588bb004256ef7.

Re-add heroku config for review apps

---

src/components/segments/CodeAcrossLink.js
src/components/segments/Interested.js
static/css/style.css

Changed the CodeAcrossLink HTML slightly, added in some CSS for it.

Tweak codeacross styles and component.

---

static/css/style.css

Slightly refactored headers in style.css and added h2 font styling. Also added Enriqueta as body font to avoid Times rendering anywhere.

Refactored headers in CSS and added h2 font styling.

---

src/components/pages/CanWeHelpYou.js
src/components/pages/WantToHelp.js
src/components/pages/WantToLearn.js
src/components/pages/WhatWeDo.js
src/components/pages/WhoWeAre.js
static/css/style.css

Issue-#175

---

src/components/segments/FooterNav.js

Fix footer links.

---

src/components/pages/WhatWeDo.js
src/components/pages/WhoWeAre.js

shuffled hero images

---

src/components/pages/CanWeHelpYou.js
src/components/pages/WantToHelp.js
src/components/pages/WantToLearn.js
src/components/pages/WhatWeDo.js
src/components/pages/WhoWeAre.js
static/css/style.css

added wrapper to body-content and styled white to achieve desired effect

added wrapper to body-content - closes #236

---

src/components/pages/CanWeHelpYou.js
src/components/pages/WantToHelp.js
src/components/pages/WantToLearn.js
src/components/pages/WhatWeDo.js

Some of the text / content was duplicated on all but one page. Now removed.

closes #244

---

src/components/segments/Projects.js
src/markdown/projects.md

Move the carousel under the projects header. - Closes #210

---

src/markdown/learning_resources.md

Fixed missing apostrophe

---

src/components/Header.js
src/components/pages/CanWeHelpYou.js
src/components/pages/OurVoice.js
src/components/pages/WantToHelp.js
src/components/pages/WantToLearn.js
src/components/pages/WhatWeDo.js
src/components/pages/WhoWeAre.js
src/components/segments/Dashboard.js
src/components/segments/Interested.js
src/components/segments/Projects.js
src/components/segments/SocialMediaLinks.js

and make a few other stylistic changes
If you haven't configured your editor to show eslint errors, you can run `npm run lint` to check for lint errors.

Clean up eslint warnings

---

src/components/segments/Projects.js
static/css/style.css

Clean up and simplify project carousel

---

package.json
src/App.js
src/NotFound.js
src/components/Header.js
src/index.js
src/routes.js
static/css/style.css

- Updated react-router to 2.0.x
- refactored the Routes out into a separate file
- modified Header to take advantage of react-router magic active route technology so nav links highlight.
- pulled App and NotFound components out of the index.js file
- General cleanup of package.json and other things.

Updated react-router and refactored app and navigation.

---

package.json
src/components/segments/Interested.js
src/components/segments/MeetupDate.js
src/components/segments/MeetupsContainer.js
static/css/style.css

Moved the Meetup calendar out into separate components, all the ajax and data manipulation is done in the MeetupsContainer, and the actual display is done in MeetupDate.
Not sure I'm following best practices with the whole return loading ? stuff : other-stuff, some feedback would be great.

Meetup Calendar

---

src/components/segments/MeetupDate.js
static/css/style.css

1. Fix weird UI issues with meetup button / hover state
2. (a) Clean up meetup calendar responsive breakpoint
(b) force horizontal calendar section, formatted calendar date to look a little nicer in a small window
(c) clean up some previously existing redundant CSS, automatically center all interested's child elements, including margins and text-align

Meetup style fix

---

src/components/segments/Interested.js

Turn the first part of Interested into a link.

---

src/components/pages/WhoWeAre.js
src/components/segments/VimeoVideo.js
static/css/style.css

New component: VimeoVideo
Changes to: WhoWeAre and style.css
The VimeoVideo now appears on the mainpage for the website.

CfD Vimeo video added

---

src/markdown/ndoch_2016.md

As titled.
@wdoug 
@codefordenver/core-contributors

updates #ndoch 2016 agenda

---

src/markdown/the_community.md

Closes #263 
Closes #256 
Updates the Flowdock link in `the_community` markdown file.

Fix broken Flowdock link

---

src/markdown/the_community.md

Closes #233 
Adds pomodoro technique link to `the_community` mardkown page.

Add pomodoro technique link to community page

---

src/components/Header.js
src/components/pages/WorkWithUs.js
src/components/segments/FooterNav.js
src/routes.js

renames can we help you to work with us, more better

---

.github/contributing.md
.github/pull_request_template.md

Adds a pull request template to have more explanations and more fun :smile:

Add pull request template

---

src/components/segments/VimeoVideo.js

Updates our homepage video to use the new one that VP Legacies created for us for 2016

Update homepage video

---

src/markdown/member_resources.md

Updates the /members page to remove some duplicate information, and organize things ever so slightly.

Small update to /members page

---

package.json
src/components/segments/Projects.js
static/css/style.css
webpack.config.dev.js
webpack.config.prod.js

Based on #293 - merge that one first
Fixes the broken carousel on /WhatWeDo page

Carousel fix

---

package.json
src/components/segments/Projects.js
static/css/style.css
webpack.config.dev.js
webpack.config.prod.js

Reverts codefordenver/code-for-denver-site#294
This broke the site:

Revert "Carousel fix"

---

src/components/Header.js
static/css/style.css

Adds a donate link to the header. We should definitely iterate on making a better UI for this.
**Larger screen**:
**Small screen**:

Add initial donate button

---

src/markdown/member_resources.md

Add note about SparkTime for tracking volunteer time

---

src/markdown/projects.md

This PR closes #[insert associated issue number here]

Projects Updated (now with proper syntax)

---

src/markdown/who_we_are.md

Changes consistent with the Mission Statement we've voted on.
This PR closes #[insert associated issue number here]

Update text on this page
